# This is a basic workflow to help you get started with Actions
name: status

# Controls when the action will run.
# Triggers the workflow on pull requests and pushes to master branch
on:
  push:
    branches: ["master"]
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "npm"
  npm:
    # The publicly used name of the job
    name: Format, Lint, Test, Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Configures a Node environment using the latest 12.x version
      - uses: actions/setup-node@v1.4.1
        with:
          node-version: "12.x"

      # Use NPM to install our project's dependancies
      - name: install
        run: npm install

      # Execute Prettier on the codebase
      - name: format
        run: npm run format:check

      # Execute ESLint on the codebase
      - name: lint
        run: npm run lint

      # Unit tests
      - name: test
        run: npm run test

      # Build our source files with the TypeScript compiler
      - name: build
        run: npm run build
      
        # Publish to the NPM Registry
      - name: publish (npm)
        uses: primer/publish@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          args: "--dry-run -- --unsafe-perm"